version: '3'
services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - '27017'
        volumes:
            - ./backend/db_data:/data/db
    
    server:
        container_name: 'api-server'
        build:
            context: './backend'
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        depends_on: 
            - 'mongo'